# Generated by Django 4.0.4 on 2022-06-11 12:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
