# Generated by Django 4.0.4 on 2022-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pizzas_category_remove_pizzas_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='min_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
